---
title: Reabilitação cardíaca
date: '`r format(Sys.Date())`'
author:
  - name: Gabriel Parisotto, MSc
  - name: Arthur de Sá Ferreira, DSc
---

<br>

# **O que são doenças cardiovasculares?**

<br>

A Organização Mundial da Saúde (OMS) considera as doenças cardiovasculares como parte de um grupo de doenças crônicas não transmissíveis (DCNT). Estima-se que 17,9 milhões de pessoas morreram por doenças cardiovasculares em 2016, representando 31% de todas as mortes em nível global. Destes óbitos, estima-se que 85% ocorrem devido a ataques cardíacos e acidentes vasculares cerebrais (AVCs).

<br>

# **Quais as causas da doença cardiovascular?**

<br>

Os principais fatores de riscos são: o tabagismo, uso abusivo do álcool, sedentarismo, hipertensão arterial, colesterol alto, alimentação inadequada e obesidade.

<br>

# **Orientação após a alta hospitalar**

<br>

•	Cuidado	com	situações	de estresse!
 
•	Evite longos períodos em jejum e tente comer de 3 em 3 horas;

•	Precisamos de sal no organismo, mas em pouca quantidade (5 g/dia);

•	Interrompa		o	consumo	de bebida		alcóolica,		cigarro, alimentos gordurosos e com alto teor	de		açúcar	(sorvetes, refrigerantes, etc);

•	150 minutos de exercício de intensidade leve/moderada por semana (caminhada, exercício ativo livre, bicicleta, atividades em
grupo);

•	Não realize exercícios em jejum, use roupas adequadas para a prática dos exercícios e sem abusar da intensidade dos exercícios;

•	Hidrate-se antes, durante e após os exercícios;

•	Faça acompanhamento com equipe	multidisciplinar (Cardiologista, Fisioterapeuta cardiovascular, Nutricionista).
 
 <br>
 
# **Orientação de atividade domiciliar**
 
 <br>
 
Exercícios aeróbicos (aquecimento, esteira ergométrica carga baixa, bicicleta ergométrica sem resistência, caminhada); alongamentos gerais; exercícios para musculatura respiratória (inspiração máxima/expiração máxima)
 